app = "vkara-api-nhan"
primary_region = "hkg"

[build]
  dockerfile = "containers/api-redis/Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
