[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:redis]
command=/usr/bin/redis-server --bind 127.0.0.1 --port 6379 --requirepass giang --save "" --appendonly no
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0  ; Disable log file rotation
stderr_logfile_maxbytes=0  ; Disable log file rotation

[program:api]
command=/app/start-api.sh
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0  ; Disable log file rotation
stderr_logfile_maxbytes=0  ; Disable log file rotation
